update to newest react admin version and fixed old code
vivid-planet/react-admin-starter pull request #11
Opened 2019-07-30 07:53 UTC by kaufmo

2019-07-30 07:55 UTC, fraxachun approved these changes

2019-07-30 08:08 UTC, nsams commented on package.json
> +        "dnd-core": "^8.0.3",
was ist das?

2019-07-30 08:08 UTC, nsams commented on package.json
> +        "react-dnd-cjs": "^8.0.3",
das sollte nicht mehr die cjs version sein, bzw ist das gar nicht notwendig da es kein peerdependency ist

2019-07-30 12:00 UTC, kaufmo commented on package.json
> +        "dnd-core": "^8.0.3",
wenn ich das nicht hinzufüge bekomm ich vom typescript immer einen error das er es nicht findet

2019-07-30 12:00 UTC, kaufmo commented on package.json
> +        "dnd-core": "^8.0.3",
Cannot find module 'dnd-core'

2019-07-30 12:01 UTC, kaufmo commented on package.json
> +        "react-dnd-cjs": "^8.0.3",
solang das noch nicht gepulished ist brauchen wir das noch so

2019-07-30 14:05 UTC, nsams commented on package.json
> +        "react-dnd-cjs": "^8.0.3",
nein, es ist keine peerDependency

und ich habs jetzt gepublished

2019-07-30 15:33 UTC, nsams approved these changes

2019-07-31 05:03 UTC, dkarnutsch requested changes

2019-07-31 05:03 UTC, dkarnutsch commented on src/App.tsx
> +                                        <Toolbar style={{ margin: "6px 0" }} />
Can we change this to styled-components or theming as well?

2019-07-31 06:29 UTC, dkarnutsch approved these changes

2019-07-31 06:30 UTC, merged