Use docker-compose for running lints
vivid-planet/react-admin-starter pull request #21
Opened 2020-02-12 12:54 UTC by nsams

2020-02-12 12:58 UTC, fraxachun approved these changes

2020-02-20 12:07 UTC, kaufmo approved these changes

2020-02-20 12:08 UTC, kaufmo requested changes
--no-deps bitte noch mitgeben

PS: im starter fehlt das glaub ich auch noch ;)

2020-02-26 12:43 UTC, nsams commented
@kaufmo done

2020-02-27 06:00 UTC, kaufmo approved these changes

2020-02-27 06:34 UTC, merged